---
- hosts: all
  vars:
    username: robbinsd
    java_packages:
      - java-1.6.0-openjdk
  pre_tasks:
  - name: Install libselinux-python
    sudo: true
    yum: name=libselinux-python state=present
  roles:
      - { role: goozbach.EPEL, epel_enabled: 0, sudo: yes }
      - { role: base, sudo: yes }
      - robbinsd
      - { role: geerlingguy.java, sudo: yes} # Stardog requires Java
      - stardog
