---
- hosts: all
  vars:
    username: robbinsd
  pre_tasks:
  - name: Install libselinux-python
    sudo: true
    yum: name=libselinux-python state=present
  roles:
      - { role: goozbach.EPEL, epel_enabled: 0, sudo: yes }
      - { role: base, sudo: yes }
      - robbinsd
